### ISSUE TITLE
ERROR:convert_radar_point_to_image.py

### ISSUE THREAD

**Issue by yxs33** [Singingkettle/SAF-FCOS#1]
作者你好，我对你的工作很感兴趣，想复现一下，环境安装和编译成功了，但在生成雷达伪图像时出现了问题
1.python tools/nuscenes/convert_radar_point_to_image.py --dataroot ./data/nuscenes --version v1.0-trainval
生成的是空的文件夹pc，imagepc01，imagepc03，imagepc05，imagepc07，
调试发现主函数的第136行没有调用convert_pcd_file这个函数，将第136行改为
fs = [executor.submit(convert_pcd_file(token, radius)) for token in
2.改后再次运行代码，第109行pc = np.loadtxt(pcd_path)报错
OSError: ./data/nuscenes/pc/RADAR_FRONT/n015-2018-07-18-11-07-57+0800__RADAR_FRONT__1531883531485149.pcd not found
因为pc文件夹是空的，所以我将pcd文件路径改为samples文件夹，即第101行改为
pcd_path = os.path.join(nusc.dataroot, pc_rec['filename'])
3.改后再次运行代码，还是109行pc = np.loadtxt(pcd_path)报错
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 370: invalid start byte
也就是说 np.loadtx读取不了pcd文件？
请问是我哪里运行有问题，还是convert_radar_point_to_image.py这个代码不是最新的版本呢？

**Comment by Singingkettle** [comment]
Please, check whether "get_pc_info" has convert the original pcd file as new pcd file, for example:

![1635394769(1)](https://user-images.githubusercontent.com/14244102/139186282-524f0442-d479-4e38-a6d2-4fe5e6162e2c.png)
Every row is a radar point

**Comment by Singingkettle** [comment]
There are some bugs in the convert_radar_point_to_image.py, but it doesn't influence the pcd file generation. Therefore, please your code carefully and set the path correctly.

**Comment by Singingkettle** [comment]
And the bug has been corrected, which adds new lines to generate "image_pc_annotations.json"
