### ISSUE TITLE
雷达点与视觉目标不对应

### ISSUE THREAD

**Issue by xiaoche-24** [Singingkettle/SAF-FCOS#2]
雷达投影图像中的点普遍在目标的下方，这是因为没有高度信息导致的嘛？我将saf应用在别的网络中效果几乎没有提升，是不是只适用于fcos呢？在别的网络中是不是可以应用别的雷达表示形式？如线形表示？

**Comment by Singingkettle** [comment]
不是这和高度没关系，雷达点在目标下方是因为数据集中雷达安装的方式导致的，没有提升的原因可能是，你需要重新调整一下你的超参数，或者雷达图像生成的方式，当时赶毕业的问题以及硬件资源限制的问题，没有做足够的对比试验，你可以针对不同的框架对融合部分做一些修改，其实本质上来说，雷达融合其实只能提升有雷达点的地方，没有雷达点的其实没有额外信息输入融合也就无从谈起，我们后面会针对这个现象做一篇新的论文，另外我们有一篇发表在IOT上的论文将雷达与视觉融合搞到了3D框上，哪里融合采用的就不是哈达玛乘积形式，（https://ieeexplore.ieee.org/abstract/document/9775166）
